// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfileWebCore.Data;

namespace ProfileWebCore.Migrations
{
    [DbContext(typeof(ProfileContext))]
    partial class ProfileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProfileWebCore.Data.ConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessKey")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(32)");

                    b.Property<string>("AccessValue")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DATETIME2(7) DEFAULT (GETUTCDATE())");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("DATETIME2(7) DEFAULT (GETUTCDATE())");

                    b.HasKey("Id");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("ProfileWebCore.Data.PokemonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("DATETIME2(7) DEFAULT (GETUTCDATE())");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("DATETIME2(7) DEFAULT (GETUTCDATE())");

                    b.Property<string>("PokemonDescription")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("PokemonHeight")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("PokemonId")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("PokemonImage")
                        .IsRequired()
                        .HasMaxLength(360);

                    b.Property<string>("PokemonImageSBack")
                        .IsRequired()
                        .HasMaxLength(360);

                    b.Property<string>("PokemonImageSFront")
                        .IsRequired()
                        .HasMaxLength(360);

                    b.Property<string>("PokemonName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("PokemonType")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("PokemonWeight")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("StatAttack")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("StatDefense")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("StatHp")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("StatSpAttack")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("StatSpDefense")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("StatSpeed")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("StatTotal")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Pokemon");
                });
#pragma warning restore 612, 618
        }
    }
}
